spring:
  datasource:
    url: jdbc:h2:file:./data/fairylearn_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
  security: # Added for OAuth2
    oauth2:
      client:
        registration:
          google:
            client-id: 1093953420579-hvtg3btvbdp6en06g56j9akpk76rjsia.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          naver:
            client-id: 9mHLQ6Nv5VTa2CCa4NOO
            client-secret: VOZ9Xg3mtD
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
          kakao:
            client-id: c87ae4a95c44099c0e06df53875253da
            client-secret: 0AJN5ZXZFw8xuJCgn1Rgn7EXQvDx1A4L
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          google:
            issuer-uri: https://accounts.google.com
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt: # Added for JWT
  secret: BmJKbUWK9LaVPT2mZCGkUDk7QsBQkUIGmGZBBOPUwXU= # Replace with a strong, base64 encoded secret
  expiration-minutes: 60 # Token expiration time in minutes
  refresh-expiration-minutes: 10080 # 7 days (10080 minutes)

bucket4j: # Added for Rate Limiting
  enabled: true
  filters:
    - cache-name: buckets
      url: /api/.* # Apply to all API endpoints
      strategy: local
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes

admin: # Added for Admin API
  token: ${ADMIN_TOKEN:dev-admin-token} # Externalized to environment variable

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.fairylearn.backend: DEBUG
