spring:
  application:
    name: backend
  profiles:
    active: local
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
ai:
  python:
    base-url: http://localhost:8000